### ISSUE TITLE
js do ie9 não está presente

### ISSUE THREAD

**Issue by arisenna** [Apiki/blanktheme#1]
E aí galerinha +-, seguinte, ativei o tema aqui e recebi warnings dos 3 arquivos de "lt IE 9", no código está buscando na pasta ghost/assets/javascripts/support/, mas essa pasta não existe na estrutura do tema. Aí fui ver, nem dentro de assets tem a pasta com os js do projeto.

Alguém esqueceu de subir isso aí?

**Comment by elvishp2006** [comment]
@arisenna Mudamos um pouco a estrutura do tema, iremos pensar como incluiremos estes arquivos. Vlw pelo feedback.

**Comment by elvishp2006** [comment]
Resolvido!
